config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  get 'products', to: 'products#index'
  get 'product/:id', to: 'products#show', as: 'product'

  resources :folders

  resource :session, only: %i[new create destroy]

  resources :users, only: %i[new create edit update]

  namespace 'admin' do
    resources :products, only: %i[index new create edit update destroy]
  end
end

app/models/folder.rb
# frozen_string_literal: true

class Folder < ApplicationRecord
  # validates :title, precence: true
  # validates :description, precence: true
end

app/controllers/folders_controller.rb
# frozen_string_literal: true

class FoldersController < ApplicationController
  def index
    folders = Folder.all
    render locals: { folders: }
  end

  def new
    folder = Folder.new
    render locals: { folder: }
  end

  def create
    folder = Folder.new(folder_params)

    if folder.save
      flash[:success] = 'Folder has been successfully created'
      redirect_to folders_path
    else
      render :new, locals: { folder: }
    end
  end

  def edit
    folder = Folder.find_by(id: params[:id])
    render locals: { folder: }
  end

  def update
    folder = Folder.find(params[:id])
    if folder.update(folder_params)
      flash[:success] = 'Folder has been successfully updated'
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(folder, partial: 'folders/shared/show', locals: { folder: })
        end
        format.html { redirect_to folders_path }
      end
    else
      flash[:error] = 'Updating error'
      render :edit, locals: { folder: }
    end
  end

  def show
    folder = Folder.find(params[:id])
    render locals: { folder: }
  end

  def destroy
    folder = Folder.find(params[:id])
    render locals: { folder: }
    # folder.destroy
  end

  private

  def folder_params
    params.require(:folder).permit(:title, :description)
  end
end

app/views/folders/shared/_form.html.erb
<%= form_with model: folder do |f| %>

  <div class="form__group">
    <%= f.label :title, class: "form__label" %>
    <%= f.text_area :title, class: "form__border" %>
  </div>

  <div class="form__group">
    <%= f.label :description, class: "form__label" %>
    <%= f.rich_text_area :description, class: "form__border" %>
  </div>

    <%= button_tag(folder.new_record? ? "Create" : "Update", class: "btn") %>
<% end %>

app/views/folders/shared/_show.html.erb
<%= turbo_frame_tag folder, target: "_top" do %>
  <div class="my-20">
    <div class="pb-10">
      <h1 class="pb-4 text-3xl text-bold"><%= folder.title %></h1>
      <p><%= folder.description %></p>
    </div>

    <div class="flex space-x-10">
      <%= link_to "Edit folder", edit_folder_path(folder), class: "btn", data: { turbo_frame: folder } %>
      <%= button_to "Delete folder", folder_path(folder), method: :delete, class: "btn",
      data: { confirm: "Are you sure you want to delete this folder?", turbo: true } %>
    </div>
  </div>
<% end %>