config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  get 'products', to: 'products#index'
  get 'product/:id', to: 'products#show', as: 'product'

  resources :folders

  resource :session, only: %i[new create destroy]

  resources :users, only: %i[new create edit update]

  namespace 'admin' do
    resources :products, only: %i[index new create edit update destroy]
  end
end

app/models/folder.rb
# frozen_string_literal: true

class Folder < ApplicationRecord
  # validates :title, precence: true
  # validates :description, precence: true
end

app/controllers/folders_controller.rb
# frozen_string_literal: true

class FoldersController < ApplicationController
  def index
    folders = Folder.all
    render locals: { folders: }
  end

  def new
    folder = Folder.new
    render locals: { folder: }
  end

  def create
    folder = Folder.new(folder_params)

    if folder.save
      flash[:success] = 'Folder has been successfully created'
      redirect_to folders_path
    else
      render :new, locals: { folder: }
    end
  end

  def edit
    folder = Folder.find_by(id: params[:id])
    render locals: { folder: }
  end

  def update
    folder = Folder.find(params[:id])
    if folder.update(folder_params)
      flash[:success] = 'Folder has been successfully updated'
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(folder, partial: 'folders/shared/show', locals: { folder: })
        end
        format.html { redirect_to folders_path }
      end
    else
      flash[:error] = 'Updating error'
      render :edit, locals: { folder: }
    end
  end

  def show
    folder = Folder.find(params[:id])
    render locals: { folder: }
  end

  def destroy
    folder = Folder.find(params[:id])
    render locals: { folder: }
    # folder.destroy
  end

  private

  def folder_params
    params.require(:folder).permit(:title, :description)
  end
end

app/views/folders/destroy.turbo_stream.erb
<%= turbo_stream.remove "folder_#{folder.id}" %>

app/views/folders/edit.html.erb
<div class="main__wrapper">
 <%= turbo_frame_tag folder do %>
    <%= render partial: "folders/shared/form", locals: { folder: folder } %>
  <% end %>
</div>

app/views/folders/index.html.erb
<div class="space-y-16 main__wrapper">
<button class="flex flex-row items-center">
  <%= link_to "Create folder", new_folder_path, class: "btn" %>
</button>

  <% folders.each do |folder| %>
    <%= render partial: "folders/shared/show", locals: { folder: folder } %>
  <% end %>
</div>

app/views/folders/new.html.erb
<div class="main__wrapper">
  <%= render partial: "folders/shared/form", locals: { folder: folder} %>
</div>