config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  get 'products', to: 'products#index'
  get 'product/:id', to: 'products#show', as: 'product'

  resources :folders

  resource :session, only: %i[new create destroy]

  resources :users, only: %i[new create edit update]

  namespace 'admin' do
    resources :products, only: %i[index new create edit update destroy]
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_one_attached :image
  has_rich_text :description

  validates :title, presence: true, length: { minimum: 3 }
  validates :description, presence: true, length: { minimum: 10 }
end

app/controllers/admin/products_controller.rb
# frozen_string_literal: true

module Admin
  class ProductsController < ApplicationController
    def index
      products = Product.all
      render locals: { products: }
    end

    def new
      product = Product.new
      render locals: { product: }
    end

    def create
      product = Product.new(product_params)

      if product.save
        flash[:success] = 'Product has been successfully created'
        redirect_to admin_products_url
      else
        flash[:error] = 'Creation error'
        render :new, locals: { product: }
      end
    end

    def edit
      product = Product.find(params[:id])
      render locals: { product: }
    end

    def update
      product = Product.find(params[:id])
      if product.update(product_params)
        flash[:success] = 'Product has been successfully updated'
        respond_to do |format|
          format.turbo_stream do
            render turbo_stream: turbo_stream.replace(product, partial: 'admin/products/shared/product',
                                                               locals: { product: })
          end
        end
      else
        flash[:error] = 'Updating error'
        render :edit, locals: { product: }
      end
    end

    def destroy
      product = Product.find(params[:id])
      flash[:success] = 'Product has been successfully deleted'
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.remove(product) }
      end
      product.destroy
    end

    private

    def product_params
      params.require(:product).permit(:title, :description, :in_stock, :price, :image)
    end
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/shared/_form.html.erb
<% url = product.persisted? ? admin_product_path(product) : admin_products_path %>

<%= form_with model: product, url: url do |f| %>
  <div class="form__group">
    <%= f.label :title, class: "form__label" %>
    <%= f.text_field :title, class:"form__border" %>
  </div>

  <div class="form__group">
    <%= f.label :image, class: "form__label" %>
    <%= f.file_field :image %>
  </div>

  <div class="form__group">
    <%= f.label :description, class: "form__label" %>
    <%= f.rich_text_area :description, class: "form__border" %>
  </div>

  <div class="form__group">
    <%= f.label :in_stock, class: "form__label" %>
    <%= f.check_box :in_stock %>
  </div>

  <div class="form__group">
    <%= f.label :price, class: "form__label" %>
    <%= f.number_field :price, class:"form__border form__border-sm" %>
  </div>

  <%= f.submit "Save", class:"btn" %>
<% end %>

app/views/admin/products/shared/_product.html.erb
<%= turbo_frame_tag product, target: "_top" do %>
  <div class="product">
    <h2 class="product__title"><%= product.title %></h2>
    <p class="product__desc"><%= product.description %></p>
    <% if product.image.attached? %>
      <%= image_tag(product.image, style: "width: 200px") %>
    <% end %>
    <p class="product__price"><%= number_to_currency(product.price) %></p>
    <% if product.in_stock == true %>
      <p class="product__stock">In stock</p>
    <% else %>
      <p class="product__stock-not">Not in stock</p>
    <% end %>

    <div class="flex flex-row items-center space-x-8">
      <div class="my-6">
        <%= link_to 'Edit', edit_admin_product_path(product), data: {turbo_frame: product }, class: "btn btn-sm" %>
      </div>
      <div class="my-6">
        <%= button_to 'Delete', admin_product_path(product),  data: {turbo_stream: true},  method: :delete, class: "btn btn-sm" %>
      </div>
    </div>
  </div>
<% end %>