config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  get 'products', to: 'products#index'
  get 'product/:id', to: 'products#show', as: 'product'

  resources :folders

  resource :session, only: %i[new create destroy]

  resources :users, only: %i[new create edit update]

  namespace 'admin' do
    resources :products, only: %i[index new create edit update destroy]
  end
end

app/views/admin/shared/_flash_messages.html.erb
<div class="main__wrapper">
<% flash.each do |key, value| %>
  <div class="flash flash-<%= key %>">
    <%= value %>
  </div>
</div>
<% end %>

app/views/admin/shared/_navbar.html.erb
<nav class="navbar">
  <div class="flex-1">
    <%= vite_image_tag 'images/company_logo.png', class: "navbar__logo" %>
  </div>
  <ul class="navbar__menu">
    <li><%= link_to 'Home', root_path, class: "navbar__link" %></li>
    <li> <%= link_to 'Products', products_path, class: "navbar__link" %> </li>
    <li><%= link_to 'Admin side', admin_products_path, class: "navbar__link" %></li>
    <li><%= link_to "Folders", folders_path, class: "navbar__link" %></li>
  </ul>

  <ul class="flex navbar__ul">
    <% if user_signed_in? %>
      <li><%= current_user.name %></li>
      <li><%= button_to 'Sign out', session_path, method: :delete, class: "btn btn-sm" %></li>
      <%= link_to 'Edit profile', edit_user_path(current_user), class: "btn btn-sm w-20 text-center" %>
    <% else %>
    <% end %>
  </ul>

  <% unless user_signed_in? %>
    <div class="flex flex-col items-end flex-1 space-y-4">
      <%= link_to 'Sign up', new_user_path, class: "btn btn-sm w-20 text-center" %>
      <%= link_to 'Log in', new_session_path, class: "btn btn-sm w-20 text-center" %>
    </div>
  <% end %>
<nav>